### ISSUE TITLE
loading indicators should be view specific

### ISSUE THREAD

**Issue by rodney757** [biocodellc/geome-ui#10]
if viewing project settings, and you click `expedtitions` or `members`, the loading indicator appears and removes all other content temporarily. This loading indicator should appear where the content is loading, and leave all other content in place.

This is because there are hooks in `app.component.js` that display the loading indicator if the state transition contains a resolvable. 

we should remove these hooks and display the loading indicator in the specific views.

**Comment by mariadeck** [comment]
Do you want to keep the hooks in app.component .js, or move them to the component itself

**Comment by rodney757** [comment]
I'd say don't worry too much about this one for now...

For future notes, the way this would need to be implemented is to have a check in the `app.component.js` hook that only sets `this.loading = true` if `hasResolvables(trans.$to()) && trans.$to() == directChildState`.

A `directChildState` is a direct descendent of the root state, and not a nested child.

This is needed so that when changing to the `Load Data` state, the loading indicator is shown until the resolvables finish.

But if we are in a nested child state ex. `projects/1/members` then it is the parent of that child that is responsible for displaying the loading indicator. In the previous example, that would be the `projects` state. This would give child states the most flexibility in determining where to show the loading indicator.

**Comment by jdeck88** [comment]
closing this issue... can re-open if urgent
