### ISSUE TITLE
EventID page has jumbled metadata

### ISSUE THREAD

**Issue by jdeck88** [biocodellc/geome-ui#102]
See attached image below where lat/lng are not together ... seems to be a random list of fields.  These should be ordered in a more sensible manner.

![image](https://user-images.githubusercontent.com/1154501/44354620-2dad9880-a45f-11e8-990a-28ca05a52a6e.png)

**Comment by rodney757** [comment]
ya, these pages are still a WIP, it's part of the photo work

**Comment by rodney757** [comment]
These pages are done now. There may still be a few tweaks we want to make, but I finished the first implementation.

These fields now appear in the same order as they appear in the project config.
