### ISSUE TITLE
Project Selector Include-Public 

### ISSUE THREAD

**Issue by mariadeck** [biocodellc/geome-ui#106]
All public projects are being included in the project selector dropdown automatically; checkbox to Include public projects isn't functioning

**Comment by rodney757** [comment]
can't reproduce...

Currently all projects are public. If your user is a member of all projects (biocode user), then they are already included. If I login w/ a different user, it works as expected

**Comment by rodney757** [comment]
ah, I see now.

if the currently selected project isn't in the users projects list & is public, then we auto-check "include-public".

I guess we should at least communicate this to the user.

We need to define the wanted behavior for the following cases:

1. !includePublicProjects and currentProject is not in the list
2. !includePublicProjects and the user is not a member of any projects

currently we auto-select "includePublicProjects" so the user isn't redirected to the home page. If you have opinions, feel free to chime in
