### ISSUE TITLE
Query interface mock-ups

### ISSUE THREAD

**Issue by jdeck88** [biocodellc/geome-ui#118]
Mock-up new query interface, get buy off from SI and then implement.
We now have the ability to query on ALL projects.  So:

projects <- provide drop-down list of projects (can we choose a "family" of projects as well, e.g. ALL Biocode template projects or ALL Dipnet template projects)
expeditions <- provide drop-down list of expeditions for a selected project

MORE SEARCH OPTIONS Change to "Switch to Advanced Search" or  "Switch to Simple Search" based on what view you are looking at.

Simple search: provide just a few fields
Advanced Search:
Event Filters
Sample Filters
tissue Filters

**Comment by jdeck88** [comment]
Simple query mock-up:
![simplequery](https://user-images.githubusercontent.com/1154501/45438423-f8662600-b66b-11e8-8e77-17b078145409.jpg)

Advanced query mock-up:
![advancedquery](https://user-images.githubusercontent.com/1154501/45438431-ff8d3400-b66b-11e8-8d91-215feba6849d.jpg)

**Comment by jdeck88** [comment]
For year in the simple query use the current layout:

![image](https://user-images.githubusercontent.com/1154501/45498762-a8e92e00-b72f-11e8-950e-e2dd3ebdc2c1.png)

**Comment by rodney757** [comment]
Question from Chris:

> Is there a way to just request specimens with images or just ones with tissues

@jdeck88 do we want to add this to the query interface. Seems like the 'has' (ex. current has fasta marker) checkboxes are useful

**Comment by jdeck88** [comment]
@rodney757  yes, i think that would be good to include.  But lets wait to see what Maria has for interface and then figure out best place to put it.
