### ISSUE TITLE
Create links to about page accordion 

### ISSUE THREAD

**Issue by mariadeck** [biocodellc/geome-ui#128]
For Projects and Data Usage, we need to go to about page and open the accordion from different links:
Link to Projects accordion group from the link in Getting Started link
Link to Data Usage Policy from angular toaster on query page

**Comment by mariadeck** [comment]
add "target:_blanks" to external links

**Comment by rodney757** [comment]
fyi, this can be done using urls like `http://localhost:3000/about#projects` and retrieving the value w/ https://docs.angularjs.org/api/ng/service/$location#hash & opening the appropriate accordion
