### ISSUE TITLE
apply md-virtual-repeat to project listing

### ISSUE THREAD

**Issue by jdeck88** [biocodellc/geome-ui#136]
Projects could get really long on the project component.  
Solution is to sort alphabetically and use [md-virtual-repeat](https://material.angularjs.org/latest/demo/virtualRepeat) to display projects.

**Comment by mariadeck** [comment]
Do you want the Uib accordion in here, or just display projects with their info immediately?

**Comment by jdeck88** [comment]
i think we still want accordian there, just use the accordian name to display the project title
