### ISSUE TITLE
Add metadata view option  to View Plate panel

### ISSUE THREAD

**Issue by jdeck88** [biocodellc/geome-ui#141]
When we view plate add an option to top of screen that has a drop-down with all metadata columns.  Can also choose, phylum, country, etc... and when chosen, instantly populate with the metadata of the chosen field.  
I do not think we need to add three different attributes as we do in the current plate viewer. 

By default selector is tissueID and if chosen, only show tissueID.  If another column is chosen show tissueID (with link) and the metadata for the chosen column.

**Comment by rodney757** [comment]
I'm only displaying sample & tissue fields for now. I'm not sure if event fields are necessary and it will make the select list that much longer.

We can easily add if event fields later if requested.
