### ISSUE TITLE
Port GGI and BWP projects to GeOME

### ISSUE THREAD

**Issue by jdeck88** [biocodellc/geome-ui#147]
Work with GGI and BWP to port projects from FIMS2.  Following is letter sent to GGI and BWP admins:

I am working on migrating all legacy biocode (aka FIMS2 or Biscicol, projects running at biscicol.org) to the GeOMe site.  GeOMe is a network of FIMS related projects and was created for several reasons: 1) make it easier to spin up new projects including the ability for a user to create a new project on demand through the UI, 2) provide better control over project configuration with ability to make changes through UI, 3) enable better collaboration amongst FIMS projects, 4) simplify management of currently 3 different FIMS codebases into one codebase.  

I’m sending this email to both GGI and BWP/ CBOL admins since the projects are very similar and the proposed changes are nearly identical.  

Several changes need to happen before migrating GGI, BWP, and CBOL projects to GeOMe. The biggest change is to adapt the flattened structure of the data model to GeOMe’s entity model which handles events, specimens, and tissues independently.  We can still provide users a single spreadsheet without requiring uploading different sheets for events, specimens, and tissues, however it does mean we need to make a few changes.  Here is my proposal: 

Events: An eventID will be hashed from event attributes.  The current eventID field becomes eventRemarks.
Specimens: Create a materialSampleID field hashed from specimen attributes.  The voucherID will maintain the voucherID name but will not be a primary key*
Tissues: tissueBarcode will be renamed tissueID

*BWP may choose to manually construct the materialSampleID key field (was voucherID) using the Dwc:triplet.  I looked at the data, however and noticed at least one spot in BWP Kenya where the voucherID referred to two different specimens.  This happened since voucherID was not enforced as unique across the project. Let me know if you need to discuss further

Some other attributes we will need to change the name.. Mostly, attributes line up well within the network since most projects adopted DwC names.  However, a few attributes require renaming:
identificationConfidence -> identificationRemarks
extractionPlateID -> 
extractionWell -> 
species -> specificEpithet
subSpecies -> infraSpecificEpithet

Finally, we can handle the data migration on our end and would propose migrating projects first to our development server, and then having you check the data to make sure it all looks good, and then we would push the changes to our production server, at which point we would disable uploads on the old biscicol server.

**Comment by jdeck88** [comment]
done

**Comment by ewingrj** [comment]
BWP still isn't ported
