### ISSUE TITLE
Update project component to handle configurations

### ISSUE THREAD

**Issue by jdeck88** [biocodellc/geome-ui#148]
The recently implemented project configuration bundles projects by general configurations, for now just Biocode and DIPnet. The project component should list the projects by each component that they fall under. To steps to accomplish this:

 * review the project and network REST services to deliver the necessary information (RJ)
 * update the project component to list projects by their configuration (Maria).  I don't think this should go into the current PR, lets wait a bit so the configuration logic to mature.

**Comment by rodney757** [comment]
all info is already there in the api calls. Just group by `project.projectConfiguration.id`
