### ISSUE TITLE
notify user to login in when clicking on plateviewer

### ISSUE THREAD

**Issue by jdeck88** [biocodellc/geome-ui#158]
if user not logged and there are no plates in a project in then a cryptic message shows up.  We just want to add text to inform user to login so they can create their first plate.    see image below

~Also, if there is only one plate in the database, we should still open with the plate selector.~ fixed

![image](https://user-images.githubusercontent.com/1154501/45920471-16483d80-be59-11e8-8126-13740648d15b.png)

**Comment by mariadeck** [comment]
close
