### ISSUE TITLE
Drop-down list of attributes not provided on Template

### ISSUE THREAD

**Issue by jdeck88** [biocodellc/geome-ui#162]
When creating a spreadsheet template, for fields with controlled vocabularies, there used to be a feature where a drop-down validation was provided in excel... that is not there anymore... would like to re-insert this feature!

**Comment by rodney757** [comment]
oops, not sure why that got turned off.

fixed https://github.com/biocodellc/biocode-fims-commons/commit/8f86cfa47996c5267a150f11d57b9387e3b8021a
