### ISSUE TITLE
Create project delete option

### ISSUE THREAD

**Issue by jdeck88** [biocodellc/geome-ui#164]
Under project Settings, create a delete option and possible an archive option.  Put them in DANGER section, as in github (see below).  probably also put private/public option in the danger section:

![image](https://user-images.githubusercontent.com/1154501/46114714-b16a4b80-c1a8-11e8-9787-5cbae4e88d93.png)

**Comment by rodney757** [comment]
cefa00f

**Comment by jdeck88** [comment]
This is done
