### ISSUE TITLE
Simplify project creation

### ISSUE THREAD

**Issue by jdeck88** [biocodellc/geome-ui#168]
1. Always clone a configuration (remove option to NOT clone)
2. Can be network approved or your own configuration (as it is now).
3. Only allow editing of rules and attributes (don't allow, for example, changing hash/no-hash identifiers)

The basic idea is want this SIMPLE to explain to someone, ideally just by having them read the "Getting Started" section of the about page.

**Comment by rodney757** [comment]
One thought is to the "Photos Module" into the wizard. Photo modules is pretty simple and I'd imagine users would want to use the geome data config with photos
