### ISSUE TITLE
Phylum listed twice when spreadsheet is generated

### ISSUE THREAD

**Issue by jdeck88** [biocodellc/geome-ui#176]
In GGI Test project (owned by Biocode), when you generate a template (taking all defaults), phylum is listed twice in the generated spreadsheet.

The column below the first phylum instance gives a drop-down list of phyla.  
The column below the second phylum instance does not give a drop-down list of phyla.

**Comment by rodney757** [comment]
this is b/c there is a required & a warning rule in the config.

I updated the api to exclude duplicate columns however
