### ISSUE TITLE
fails to update project from private to public

### ISSUE THREAD

**Issue by jdeck88** [biocodellc/geome-ui#177]
Tested on GGI Test / owned by Biocode, attempt changing project from private to public.  Gives server error message .

In developer tools, request payload:

{projectId: 37, projectCode: null, projectTitle: "GGI Test", created: "2018-10-10 17:19:40",…}
config: {entities: [{type: "DefaultEntity",…}, {type: "DefaultEntity",…}, {type: "DefaultEntity",…}],…}

response:

Unrecognized field "subscribed" (class biocode.fims.models.User), not marked as ignorable (7 known properties: "lastName", "userId", "institution", "password", "email", "username", "firstName"])
 at [Source: (org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$UnCloseableInputStream); line: 1, column: 480] (through reference chain: biocode.fims.models.Project["user"]->biocode.fims.models.User["subscribed"])

**Comment by rodney757** [comment]
fixed in https://github.com/biocodellc/biocode-fims-commons/commit/d2408c1199fb056121fc754a92f88169109ca9dd
