### ISSUE TITLE
query interface bad map

### ISSUE THREAD

**Issue by jdeck88** [biocodellc/geome-ui#185]
When initializing the query interface, the map appears all wonky:

![image](https://user-images.githubusercontent.com/1154501/47444163-b8b25400-d76a-11e8-87bb-6a464d587baa.png)

If you resize the window it then works properly.  I believe this behaviour started when we moved servers.... it appears to not be finding some javascript files...  the console window gives errors like the following:

DevTools failed to parse SourceMap: https://deploy-preview-180--geome-develop.netlify.com/js/autotrack.js.map

**Comment by mariadeck** [comment]
src/app/components/map.component.js
Line 16:
increase $timeout() delay from 0 to 50 milliseconds makes the map render properly. But maybe $timeout isn't the best permanent solution here.

From leaflet Docs: 
[Make sure all the code is called after the div and leaflet.js inclusion](https://leafletjs.com/examples/quick-start/)

I don't know why changing servers affected this... but it seems like the new servers are running the code faster than before...

**Comment by rodney757** [comment]
Thanks @mariadeck. I made a commit w/ that change & updated the deployed sites. This shouldn't have anything to do w/ the new servers. Probably some other change broke this. I'll do a `git blame` to find the bad commit at some point, as it would probably be better to be able to render it sooner.

But that fix will work for now
