### ISSUE TITLE
Some test points in oregon give 404 when clicking on event and sample details

### ISSUE THREAD

**Issue by jdeck88** [biocodellc/geome-ui#186]
Two Test points that John loaded in Oregon give 404 errors when clicking on them.

**Comment by rodney757** [comment]
was this running the app locally? b/c that feature doesn't really work locally due to the webpack server that serves the app, but will work when deployed

**Comment by jdeck88** [comment]
it was running on the netlify preview... now, i cannot replicate. closing issue.
