### ISSUE TITLE
Unable to save tissues on plate viewer

### ISSUE THREAD

**Issue by jdeck88** [biocodellc/geome-ui#194]
Created a new project in Geome (using Biocode Template) called JohnBiocodeTest1.
Loaded some sample data using a spreadsheet with two tissues
Tried to create a third tissue in the plate viewer ... unable to save data?

Also, tried deleting a tissue and it didn't prompt for confirmation (i thought we had this previously).

**Comment by rodney757** [comment]
the delete confirmation only shows if there is more tissue data then "tissueID", "tissuePlate", "tissueWell". If there is only that data, then the tissue can easily be re-created via the plate viewer. If other data exists, then the tissue was uploaded via a spreadsheet.

Can you give more detail steps to reproduce the plate viewer issue. I tried creating a new plate & editing an existing one in "Test Project" and it worked. (Production env)

**Comment by jdeck88** [comment]
See this.....
https://drive.google.com/file/d/1Eicx4ib4IqjuSkcFQgV6DTKKi1H9CFP5/view

**Comment by jdeck88** [comment]
Ah.... this issue happens when the materialSampleID is only 1 character.
I was testing with materialSampleID = 1 and materialSampleID = 2. 
I just tried "jd1" and it worked.

**Comment by jdeck88** [comment]
This has been fixed.
