### ISSUE TITLE
ExpeditionCode Message when re-loading a sheet

### ISSUE THREAD

**Issue by jdeck88** [biocodellc/geome-ui#196]
To recreate:
1. download template w/ just minimum required fields, fill out some data
2. upload this spreadsheet.
3. export the spreadsheet and add a row of data using just the minimum required fields (NOTE: when we re-download an expedition i now see ALL of the available fields instead of just the minimum required fields... thats OK though).
4. re-upload the spreadsheet (option to re-place data) and i get a message "MisMatched Expedition Code(s)".  (see image below).  If i remove the last three columns (bcid, expeditionCode, projectID) i can make the message go away.  

I don't think we can expect users to update the BCID, expedition code, projectID columns when adding new rows to a re-used expedition.   Can we just have the validator ignore these fields on upload???  i think they are just useful on the user side. 

![image](https://user-images.githubusercontent.com/1154501/48440360-9003f580-e73d-11e8-81ab-8bb287b20a24.png)

**Comment by rodney757** [comment]
okay, this is fixed in develop.

We still issue a warning if the expeditionCode doesn't match, but we exclude empty expeditionCodes from that warning.

bcid & projectId are ignored. So is the expeditionCode, other then the sanity check warning if uploading to a different expedition.
