### ISSUE TITLE
Sort Query Results Table

### ISSUE THREAD

**Issue by jdeck88** [biocodellc/geome-ui#232]
Sort table in query results.  Currently uses sly table, but need to change this in order to allow sorting. project-config-attributes.html uses an md table that is sortable. This is a bit involved. will need to wait.  see https://github.com/daniel-nagy/md-data-table for implementation

**Comment by jdeck88** [comment]
From RJ:
Hmm, so the issue is that we were previously using sly-repeat b/c rendering 10k dom elements is extremely slow. sly-repeat uses virtual dom tricks to only render what is in the view and update that, thus only rendering ~50 dom elements & then updating those as needed.

sly-repeat expected the data to be in an array for each row.

I'm pretty sure that md-data-table expects the data to be an array of objects. Thus the sort is attempting to sort by object property (column name) but not finding it.

You'll need to restructure the data to be an array of object. I'm not sure if we'll run into rendering issues when 10k results are returned or not (might be okay b/c the table is paginated). We'll have to try it.

You may also need to switch to the md-data-table paginator, instead of the current. Search the docs for "Example: Client Side Pagination Using ngRepeat".

RJ

**Comment by ewingrj** [comment]
fixed in 2275192cd392d56e9b136240fccda9b0c11069b5

**Comment by ewingrj** [comment]
@jdeck88 The new table pagination show the total results. Since screen real-estate was a concern, do we want to remove the recently added "total" at the top?

**Comment by jdeck88** [comment]
Awesome!  screen real estate was mentioned on the individual record page but not on query results... i think we should keep that total at the top just to make it more obvious to the user.
