### ISSUE TITLE
date issue in submitting to genbank

### ISSUE THREAD

**Issue by jdeck88** [biocodellc/geome-ui#236]
From: Giacomo Bernardi [bernardi@ucsc.edu](mailto:bernardi@ucsc.edu)Subject: Re: geome-db access requestDate: April 2, 2018 at 10:56:45 PM PDTTo: Eric Crandall [ecrandall@csumb.edu](mailto:ecrandall@csumb.edu)Cc: Michelle Gaither [michellergaither@gmail.com](mailto:michellergaither@gmail.com)

## in Geome, I entered the date as requested, in three columns.  It is to be entered in double digits for day and month, and four digits for year.When I do that, it might work if day and month happen to have two digits, but I had 04 01 2012 and in a tsv format of excel, it ended up being shortened to 4 1 2012.  I tried everything to keep the double digit format but it did not work (formatting the column as text instead of number for example).Geome did not give me a warning signal about it so I did not worry too much.when uploaded into GenBank, the three columns are pooled in a single one and the date showed as 4/1/2012.  This format is not acceptable by Genbank they want 04/01/2012maybe there is a trick to it, but I did not find it.  The formats allowable by excel are many, but mm/dd/yyyy is not one of them, strangely enough.a format that works for excel AND genbank is 1-April-2012.  I selected that and it worked fine.  so this was a very very minor nuisance.I would not have even mentioned it, but I thought why not, it might be a very simple coding thing to change.and again, this might be entirely my mistake anyway….

**Comment by ewingrj** [comment]
Should be fixed in biocodellc/geome-db@1a1d7f83360ee5a03a8193d223d33c44aebae3fe
