### ISSUE TITLE
FIMS metadata on the sample, tissue, event records

### ISSUE THREAD

**Issue by jdeck88** [biocodellc/geome-ui#241]
I don't believe ALL of the metadata for each entity is being displayed.  Under this issue, investigate potential fields and ensure everything is displayed.

**Comment by ewingrj** [comment]
for query results?

**Comment by jdeck88** [comment]
I"m talking about the individual Record pages.... I *think* not all of the available fields are being displayed here...

**Comment by ewingrj** [comment]
Not all available fields, but it should be displaying all fields with data

**Comment by jdeck88** [comment]
This is not an issue any longer
