### ISSUE TITLE
Photo Filenames Unique value constraint issue

### ISSUE THREAD

**Issue by jdeck88** [biocodellc/geome-ui#247]
From Chris Meyer:

Error: Unique value constraint did not pass

"photoID" column is defined as unique but some values used more than once: "_2", "_3", "(3)", "_2", "(2)", "_2", "_2", "_2", "(1)", "_2", "(4)", "_2", "(3)", "_2", "_2", "(2)", "(5)", "(1)", "(1)", "_2", "(4)", "(2)"

Hi Guys - I think the above error is going to be problematic moving forward if it doesn’t allow us to upload these. Many times different cameras are used or people rename files individually before uploading - as is the case here for the Dutch Harbor stuff or Abby is also running into this issue with DROP images.

It seems the photo uploader, in addition to checking the uniqueness of the complete string (and attaching to the correct materialSampleID), is then also looking at the uniqueness of the trailing string AFTER the “+” sign. I don’t see why this needs to be locally unique or globally unique, etc. I see this in the downloaded tab with photos as the column labeled:

“photoID"

We seem to be getting lots of photos rejected for this reason - the tailing end after the “+” should certainly not be used as the PhotoID field (as it may not even exist).

Ideas?

Hope that makes sense

For instance, I think if we have a series of photos labeled:

BCURA_3000+DSC001.jpg
BCURA_3000+1.jpg
BCURA_3000+DSC002.jpg

and

BCURA_3001+DSC003.jpg
BCURA_3001+1.jpg
BCURA_3001+DSC002.jpg

the uploader will reject the last 2 (BCURA_3001+1.jpg and BCURA_3001+DSC002.jpg) because the tailing string is the same. This will happen all the time, as evidenced with our first two upload attempts.

**Comment by jdeck88** [comment]
Another comment from Chris Meyer:
Thanks - I think this would support the previous idea to create new PhotoID field based on the mateiralSampleID and then a uniquely minted string (like the tissues or ExtractionID do, just iterate a number with some sensible prefix like “photo” So my examples would be come BCURA_3000_photo001, BCURA_3000_photo002, etc.

**Comment by ewingrj** [comment]
okay, this is fixed in develop. biocodellc/biocode-fims-photos@9ad3e045e35409c9387e6a1a705114cc07c4f640 and b1067ce

PhotoEntity's have the option to set `generateID` like Tissue's.

The bulk photo uploading has a checkbox that can be selected for an upload "Auto-generate IDs". If selected, the pared id from the filename will be ignored, and an id will be generated.
