### ISSUE TITLE
About page "Project & Configurations" issues

### ISSUE THREAD

**Issue by ewingrj** [biocodellc/geome-ui#249]
1. ~~Smitionion Institution Barcoding isn't shown~~
2. When expanding the config, the projects get cutoff and doesn't scroll

**Comment by ewingrj** [comment]
it's not scrolling in chrome 73 but works w/ 72

**Comment by jdeck88** [comment]
This issue has been bypassed by recent changes that promote the configuration descriptions to the top of the about/getting started page...
