### ISSUE TITLE
expeditionProperties in downloaded files?

### ISSUE THREAD

**Issue by jdeck88** [biocodellc/geome-ui#263]
If a project adds expedition-level property, how do we make this useful and workable?  Currently, i beliee the only place this information is visible is in the expedition list that only the expedition owner can see (so not super useful). 
Some approaches:
1.  Add each expedition property to the event data download.  however, this can be confusing to the user if data is downloaded from an already populated expedition and it shows up as an event property.
2.  Another option is to add it to the project overview dashboard... would need to find all available expedition properties and iterate through them and add them to dash-board as a column and display values in column form.
3. We can add this field to the JSON output on returned data from query... JSON does not populate the excel spreadsheet downloads, but it does get sent to the biocode-lims plugin, and we can make it an accessible field from the lims.

My reading of this is that we should go with both option #2 and #3 above

**Comment by ewingrj** [comment]
Hmm, I guess it kinda depends on how users want to use the data...

Did you hear our BOEM wants to use the data? Do they want to query on it? Or just access from LIMS?

**Comment by jdeck88** [comment]
[offline conversation at the moment... will post the summary here when done]

**Comment by jdeck88** [comment]
This is not a significant issue currently, shelving..
