### ISSUE TITLE
Create URL links for projects and expeditions

### ISSUE THREAD

**Issue by jdeck88** [biocodellc/geome-ui#288]
Need to create a URL endpoint for opening up a particular project... For example 

https://geome-db.org/workbench/{project ID}

opening the project overview, and ...

https://geome-db.org/workbench/{project ID}/{expeditionCode}

opening up an expedition metadata page

**Comment by ewingrj** [comment]
You can link to a project currently by using a `projectId` query param

**Comment by jdeck88** [comment]
do you have an example of that syntax?  i keep getting 404s

**Comment by ewingrj** [comment]
https://geome-db.org/workbench/overview?projectId=1
