### ISSUE TITLE
better error message for missing expeditionCode on multiexpedition upload

### ISSUE THREAD

**Issue by jdeck88** [biocodellc/geome-ui#289]
When uploading multi-expedition data from a sheet, all rows need an expeditionCode.  
The system actually DOES say when it encounters no expedition code on a multi-expedition upload: "... one or more records are missing an expedition Code. Please ensure that all records have an expedition code specified"

However, we can be more clear in this case, some example text (and need to edit this message for clarity first!!):

"... one or more records are missing an expedition Code.   When uploading data from multiple expeditions, each record in the [EVENT? SAMPLE?] sheet must have a pre-existing expedition code specified for all records.   You can obtain a list of expedition Codes by first downloading a worksbook generated for your project from Geome, either through the Project Overview or from the Query page, and updating records.  If you need to insert NEW records, first generate them on a new or existing single expedition."

**Comment by ericcrandall** [comment]
I don't understand the last sentence. Pretty sure I generated a new expedition by simply including the name in the excel workbook...

updated to add some more clarifying text:

"... one or more records are missing an expedition Code. When uploading data from multiple expeditions, each record in the [EVENT? SAMPLE?] sheet must have a pre-existing expedition code specified for all records (in a field called expeditionCode). You can obtain a list of all expedition codes for your project by first downloading a workbook generated for your project from GeOMe, either through the Project Overview or from the Query page, and updating records. If you need to insert NEW records, first generate them on a new or existing single expedition."

**Comment by ewingrj** [comment]
fixed in biocodellc/biocode-fims-commons@2ead0f7
