### ISSUE TITLE
Order taxonomy sensibly in specimen view

### ISSUE THREAD

**Issue by jdeck88** [biocodellc/geome-ui#290]
See for example: https://geome-db.org/record/ark:/21547/CgI2BIOMAR_5001

taxonomy has no order. .. we need to group taxonomy in the proper heirarchy.  
e.g. phylum, subphylum, order, suborder....
currently it is random.

**Comment by ewingrj** [comment]
This is controlled by the config. So it just needs to be ordered correctly there

**Comment by jdeck88** [comment]
ok, forgot about that... updated config in biocode...
