### ISSUE TITLE
photo zip archives compressed with MacOSX finder's compress utility gives server error

### ISSUE THREAD

**Issue by jdeck88** [biocodellc/geome-ui#292]
The attached zip archive contains a single photo.  
Try loading this to "John Biocode Config Test Project" using the Biocode account on Geome Production. 

What i get is a server error that complains about a NullPointerException.

However, if i take this archive and extract it, then remove the resource fork dir under __MACOSX and zip using the command-line on the mac (w/out the resource fork), the same file is successfully loaded.

[RICA_2016_PLD_1A_P1T+small.jpg.zip](https://github.com/biocodellc/geome-ui/files/3210874/RICA_2016_PLD_1A_P1T%2Bsmall.jpg.zip)

So, per my tests any directories compressed using Mac's compress utility (when using the finder) doesn't work.  This was tested on both John's and Chris's macs.  However, Chris says he has been using this compress utility for awhile without issues....

**Comment by ewingrj** [comment]
fixed in biocodellc/biocode-fims-photos@79a49ff1368f71d3d53f8ec65d1039175afcffc6
