### ISSUE TITLE
Simplify Configuration Options

### ISSUE THREAD

**Issue by jdeck88** [biocodellc/geome-ui#294]
After spending a week at the GSC meetings and talking to lots of folks, there is still much confusion about Geome’s current configuration options, even among folks who are familiar with the software.  After thinking about this a lot, I’ve come up with the following proposal aimed to 1) simplify things so user’s can immediately understand what is happening, 2) enable limited customizations for any user, 3) create perhaps a better model for offering subscription features.

  1. Synchronized Configurations become “teams”.  A team is a group of people that work together.  Users are invited to join a team with organizations paying a subscription cost to manage multiple users on a team (and perhaps also have the option to upload photos).   In the new model, a user would need to be invited to join a team (synchronized configuration) and then we have the obvious path of offering enhanced features to the team configurations.  Would need another db table to track members of configurations.

 2. Unsynchronized Configurations become “independent projects”.  Open to the public to create and configure but with some limitations:
    a.      Format: user selects either a single sheet or multi-sheet format.  Once the user selects the format, the more obscure options for setting hashed/no-hashed id’s, project id’s unique across project, worksheet names, and unique keys are not even offered as options (they will be just set in background).  This way we limit the number of possible data format permutations and eliminate user confusion over these options
     b.      Attributes & Rules: make attributes and rules available to creating users for customization.
    c.      Single user: only one user per project.

The “New Project” Creation page then becomes
  1. Set Project Title/Description
  2. Set Team option (we may not even have to offer this on the UI/could happen all on email)
  3. Or, If not part of a team select Independent Project option: 1) Choose your format (single or multi sheet), 2) Select your attributes & rules, 3) Finish

Most of these changes I think are just UI changes but we lets talk.

**Comment by jdeck88** [comment]
I was thinking of an easier way to implement this... 

Start with Slider that says:
I want to join an existing team: Yes/No.
If YES: then show biocode, cbol, dipnet configurations.  (for now, joining these is free... but will need invite in future.)  These are all synchronized configs... don't need to show the option about synchronized or not... just create project.

if NO: then show just single sheet and multi-sheet options.

Then, remove "keep configuration in sync"  option. these all NOT be in sync.  Show, however, an advanced options.  

A few other things: 
remove the "network approved?" toggle under master configuration.... confusing option.
For the single/multi sheet configurations don't need to display information about project configuration under project overview... it is the same.

**Comment by ewingrj** [comment]
okay this is done in 34449b833fae1e6b5df8301eb9d9ed8f23e58a11

I implemented something more similar to the original issue as that was simpler.

You'll need to login as a user **other then** Biocode to see what a non admin user sees.

1. I don't think we'll need to "unsynchronize" any existing projects.
2. Can you update the getting stated section on the about page?

**Comment by ericcrandall** [comment]
1.	When I started configuring my project and chose a configuration, the website hung for times between 5 seconds and 2 minutes. 

2.	Maybe change “NexGen Module” to either "MPS Module" or "Massively Parallel Sequencing", or Second and Third Generation Sequencing Module”. 
	“Include fields for associating sequencing data FROM ANY METHOD THAT GENERATES FASTQ FILES with your tissues. Adds the ability to generate NCBI SRA submission packages from uploaded metadata"

3. Change “Barcoding Module” to “Sanger Sequencing Module”

	“Adds the ability to upload FASTA sequences that will be stored in GEOME”


4. Are you sure allowing the definition to be edited is a good idea?

"By default, the eventID is only unique within an expedition. When selected, the eventID will be unique across all expeditions within the project. MOST PROJECTS WILL WANT TO USE THE DEFAULT SETTING.

5.
For all of the Entity Tables:
"The available attributes for Event are listed below. You can choose which attributes you would like to appear on your spreadsheet templates. DE-SELECT ALL ATTRIBUTES FOR WHICH YOU ARE *SURE* YOUR PROJECT WILL NOT BE COLLECTING METADATA. ATTRIBUTES CAN BE DESELECTED MORE TEMPORARILY WHEN GENERATING TEMPLATES” You can also edit the definition and attribute group along with changing the default column order. ATTRIBUTE GROUPS SIMPLY ORGANIZE YOUR ATTRIBUTES WHEN GENERATING METADATA TEMPLATES AND HAVE NO IMPACT ON THE DATA THEMSELVES. Attributes that are required by GEOME can not be disabled.”

6. For Tissue, under Auto-Generate ID?
“Check this box if you would like GEOME to auto-generate tissueIDs from your materialSampleIDs”

7. There needs to be some text on the “about" page about what expeditions and projects are. Even better if there can also be a shortened version on the project wizard page. I can write this if you want.

8. All of the customization options are great but really make having more documentation essential. I can help write this. Its pretty obvious to me how everything works, but I am picturing my students from my practical computing course… they would have no clue… some of them even after taking the course. Eventually I will also make a new upload video too..

**Comment by jdeck88** [comment]
This has been implemented in develop.  Mostly done.  Remaining issues are covered elsewhere.
