### ISSUE TITLE
Create a faq

### ISSUE THREAD

**Issue by jdeck88** [biocodellc/geome-ui#302]
Some questions seem to be asked alot.  We deserve an FAQ that we can point to in order to answer recurring questions.  Here is a good one to start with (and we should clean up the text here to make it more readable).

Most configurations let you copy all of the sample metadata and change just some of the tissue metadata which enables users to enter multiple tissues for a single parent sample.    Thus, if you load your spreadsheet with the altered tissueID (and which shares identical sample metadata, including materialSampleID) and look at the project overview you will see 51 samples and 52 tissues.... 2 tissues have the same parent.   This is what the system is supposed to do: enable multiple child tissues for the same parent.
BTW:  the system performs a number of sanity checks to make sure mistakes are not made, e.g.  1) If a materialSampleID is entered twice and the sample metadata is not the same, it throws an error.  2) If a materialSampleID and sample metadata matches between two rows as well as  all of the tissue metadata (essentially a duplicate row) then an error is thrown (this is the error your saw about tissueID unique constraint failure).  Only when the sample metadata matches exactly and the tissue metadata and/or tissueID is different then the data can pass validation.

**Comment by mariadeck** [comment]
Where would you like to put the faq? 
It seems like the easiest place to put it would be in its own accordion tab on the about page.

**Comment by jdeck88** [comment]
i just added it this morning...
