### ISSUE TITLE
Project creation hang

### ISSUE THREAD

**Issue by jdeck88** [biocodellc/geome-ui#313]
When creating a project, clicking "Next" after choosing data format hangs the browser until another feature is clicked... wait times if not clicking somewhere else is 20 seconds to 2 minutes.

**Comment by ewingrj** [comment]
quick fix attempted in f77b3b64a2b2a16101511edc63d15b70b57d3fc9. We'll see if it works

**Comment by jdeck88** [comment]
This seems to be working better.  If it comes up again, we can reopen
