### ISSUE TITLE
hasPhoto search under-represents and random results

### ISSUE THREAD

**Issue by jdeck88** [biocodellc/geome-ui#328]
searches for "hasPhoto" (i only tested with sample)  not returning all results and producing somewhat random counts on each query.  I traced this back to core postgres:

Specifically, in the where clause, this construct is problematic:
sample_photo.data ? 'photoID'

(NOTE: The parameterized SQL had this as  "sample_photo.data ?? :2"  I was not able to decipher what the ?? meant so assuming it translated to just a single ?)

If i change this syntax to 
sample_photo.data ->> 'photoID' is not null

which i think is what we are after, i get many more records with photos and the result is the same every time.

SQL:

SELECT Sample.data AS "Sample_data", Sample_entity_identifiers.identifier AS "Sample_rootIdentifier", expeditions.expedition_code AS "expeditionCode", expeditions.project_id AS "projectId", Sample_Photo.data AS "Sample_Photo_data", Sample_Photo_entity_identifiers.identifier AS "Sample_Photo_rootIdentifier"
FROM network_1.Sample AS Sample JOIN expeditions ON expeditions.id = Sample.expedition_id JOIN network_1.Event AS Event ON Event.local_identifier = Sample.parent_identifier and Event.expedition_id = Sample.expedition_id LEFT JOIN network_1.Sample_Photo AS Sample_Photo ON Sample_Photo.parent_identifier = Sample.local_identifier and Sample_Photo.expedition_id = Sample.expedition_id LEFT JOIN entity_identifiers AS Sample_entity_identifiers ON Sample_entity_identifiers.expedition_id = Sample.expedition_id and Sample_entity_identifiers.concept_alias = 'Sample' LEFT JOIN entity_identifiers AS Sample_Photo_entity_identifiers ON Sample_Photo_entity_identifiers.expedition_id = Sample_Photo.expedition_id and Sample_Photo_entity_identifiers.concept_alias = 'Sample_Photo'
WHERE
Sample.local_identifier ILIKE '%PEER%'  and
--Current search restriction outputs unpredictable and limited results, not sure what is happening
--sample_photo.data ? 'photoID'
-- This one looks for a photoID explicitly and provides, i think, all of the results
sample_photo.data ->> 'photoID' is not null
AND expeditions.project_id IN (70, 71,72,73,74,76,77,78,79,80,112,81,114,82,125,83,131,75,13,40,41,61,90,67,1,89,12,85,122,107,111,68,69)
--AND expeditions.project_id IN (78, 70)
AND expeditions.public = true
ORDER BY Sample.local_identifier, Sample.expedition_id OFFSET 0 LIMIT 100000

**Comment by ewingrj** [comment]
this is actually a bug in postgres. I tried locally and the results are correct, but on the production server they are not. I'm going to update postgres to see if that resolves the issue, but waiting on an email from Matthew regarding the apt repository proxy

**Comment by jdeck88** [comment]
This is fixed
