### ISSUE TITLE
Clicking on definitions bring to section that actually displays the definition

### ISSUE THREAD

**Issue by jdeck88** [biocodellc/geome-ui#339]
The template definitions are kind of long now so when you click "DEF" for a field that displays further down the list, it is not apparent that there is even a definition there.  We should implement a bookmark so the browser goes to the definition itself when a user clicks the DEF field for a definition that is further down the list.

**Comment by ewingrj** [comment]
hmm, this used to be sticky (definition column was always visible) in the not too distant past. Need to use git bisect to determine which commit broke it.

**Comment by mariadeck** [comment]
commit 07decc4e12aea8bb9c7b71e1b0eb3e2c83c31594 
https://github.com/biocodellc/geome-ui/commit/07decc4e12aea8bb9c7b71e1b0eb3e2c83c31594
breaks this.
