### ISSUE TITLE
enable BOOLEAN searches in advanced query

### ISSUE THREAD

**Issue by jdeck88** [biocodellc/geome-ui#344]
Currently, the following fields implement BOOLEAN data type:
traditionalKnowledgeNotice
tissueBlocked
hasScale

When you query these fields in advanced query, nothing comes up... need to implement boolean datatype searches in the UI.

**Comment by mariadeck** [comment]
So it seems like the easiest way to do this is to make all Boolean attributes have network lists of true/false which is what traditionalKnowledgeNotice already has but not tissueBlocked or hasScale. Is that what we want?

**Comment by jdeck88** [comment]
I think we should use the dataType = BOOLEAN to indicate the type of search.   So search for datatype=BOOLEAN to indicate the type of search.

Using the network list attribute of trueFalse was only put there so the user entering data on a spreadsheet would list the TRUE/FALSE option as a drop down in the cell.
