### ISSUE TITLE
Template Generation Sorting

### ISSUE THREAD

**Issue by jdeck88** [biocodellc/geome-ui#372]
This is similar to #182 but different... individual fields with a specified sort order in the configuration.  The following examples use this project:

https://geome-db.org/workbench/overview?projectId=174

![image](https://user-images.githubusercontent.com/1154501/62141984-5f9bc180-b2a2-11e9-92b1-6a3c3aebc5f1.png)
defines genus, specificEpithet, infraspecificEpithet in the correct order.  The generated spreadsheet follows the correct order:
![image](https://user-images.githubusercontent.com/1154501/62142029-7510eb80-b2a2-11e9-8645-7c5a789b0fb6.png)
However, the generate template window does not follow the correct order:
![image](https://user-images.githubusercontent.com/1154501/62142059-7fcb8080-b2a2-11e9-8afd-3bc40fb6aaf4.png)

**Comment by mariadeck** [comment]
Ok, I had alphabetically ordered those when I worked on #182 but I can undo that
