### ISSUE TITLE
when querying Sample filter "traditionalKnowledgeNotice", the list options are empty

### ISSUE THREAD

**Issue by ewingrj** [biocodellc/geome-ui#378]

**Comment by mariadeck** [comment]
the traditionalKnowledgeNotice list is named 'trueFalse'
The list name should be titled 'traditionalKnowledgeNotice'

this is a network list, so I'm not sure how to edit it, could you let me know?

**Comment by ewingrj** [comment]
the list can be named anything. Doesn't have to match the attribute name.

You have to find the controlled vocabulary rules to match the attribute to the list

**Comment by mariadeck** [comment]
I've changed the advanced query to return boolean list options as 'true', 'false', which fixes this issue, but would you like me to change the returned list for future lists that aren't booleans and don't match the attribute name??

**Comment by ewingrj** [comment]
yes, please change
