### ISSUE TITLE
Need fully resolvable BCID expressed in output file

### ISSUE THREAD

**Issue by jdeck88** [biocodellc/geome-ui#382]
BCIDs should be fully qualified as HTTP URIs in output files.. Most people using the output data (in expedition downloads and in SRA submission packages) will not know to resolve them at n2t.net.  

For example:
Samples loaded into SRA from the GEOME submission package have BCIDs, which are used in linking, but they begin with ark:  only.  They should be fully specified with the HTTP URI.

An example is at:
https://www.ncbi.nlm.nih.gov/biosample/10240493

![image](https://user-images.githubusercontent.com/1154501/62562852-c2f39980-b836-11e9-826f-280851aef596.png)

It specifies the bcid as: 

ark:/21547/BdF2Stegastes_nigricans_94

but should be:

https://n2t.net/ark:/21547/BdF2Stegastes_nigricans_94

--

--

**Comment by ewingrj** [comment]
All file downloads now contain a fully resolvable bcid, including csv, excel, etc
