### ISSUE TITLE
SRA required fields

### ISSUE THREAD

**Issue by jdeck88** [biocodellc/geome-ui#384]
SRA asks for a set of fields that are somewhat unique... however, the user may not be aware of what these are:

From Kim Andrews:
I'm wondering if it might be helpful if the list of attributes on the Geome website includes some information for each attribute as to whether it will be included in the BioSample-attributes.tsv file, so that researchers can make sure they include the attributes they want to go into SRA. Otherwise people might not end up taking advantage of Geome's functionality and just load everything into the SRA manually... or else they might just never notice that the BioSample-attributes.tsv file doesn't contain all the info they want in the SRA.

So, to solve this, we should have a feature that identifies the fields for SRA submission.... E.g. during project creation, we could have an SRA  attribute set that identifies the fields that will be going into SRA, which are:

sample_name	
sample_title	
organism	
collection_date	
geo_loc_name	
tissue	
biomaterial_provider	
collected_by	
depth	
dev_stage	
identified_by	
lat_lon	
sex	
breed	
host	
age	
bcid	(supplied only by geome)

The other option here is to just supply all the field names generated by GEOME regardless of whether they are in the SRA suggested set.

**Comment by jdeck88** [comment]
I think the 2nd option will be easier to implement.... the solution would be to add ALL metadata fields that have values in them for this project and use the column name as the key and the value as the value.

**Comment by ewingrj** [comment]
added all data in biocodellc/geome-db@1a1d7f83360ee5a03a8193d223d33c44aebae3fe
