### ISSUE TITLE
Truncate project title if too long

### ISSUE THREAD

**Issue by ewingrj** [biocodellc/geome-ui#390]
Currently if the project title is really long, it will start to overlap with the menu items in the header. We need to truncate this title. Ideally setting a truncate width for each breakpoint that bootstrap provides.

<img width="1429" alt="Project title overlapping menu options" src="https://user-images.githubusercontent.com/30963004/62992281-bad3c500-be07-11e9-99d8-50277fab86e3.png">

**Comment by albarqmaria** [comment]
Fixed in PR #409
