### ISSUE TITLE
Bounding box query across international date line returns all samples

### ISSUE THREAD

**Issue by ericcrandall** [biocodellc/geome-ui#392]
Searched for genus=Linckia specificEpithet = laevigata and drew bounding box from Great Barrier Reef past Fiji (over the international dateline). The query returned Linckia samples in Indonesia and to the west. This likely has to do with decimalLongitude switching to negative as you move eastward across the international dateline into the western hemisphere.

In any bounding box that doesn't cross the dateline, the decimalLongitude value in southWest will be smaller than the value in northEast. A bounding box that DOES cross the international dateline will have decimalLongitude value in southWest be LARGER than the value in northEast. In this latter case, one can temporarily add 360 degrees to all negative values (in the western hemisphere)... not really sure how you would implement this.

**Comment by jdeck88** [comment]
There is a trick in the API for this where we expand the decimalLongitude query params in cases where the javascript detects it crosses the international dateline )see the Event.decimalLongitude parameters:

A sample query looks like this:

https://api.geome-db.org/records/Sample/json?limit=10000&page=0&access_token=jD53C85Q5SaeUU6T4y6M&networkId=1&q=_projects_:1+and+((Event.decimalLongitude+%3E=+158.1035614013672+and+Event.decimalLongitude+%3C=+180)+or+(Event.decimalLongitude+%3C=+-152.4565887451172+or+Event.decimalLongitude+%3E=+-180))+and+Event.decimalLatitude+%3C=+22.684984142872107+and+Event.decimalLatitude+%3E=+17.277218735781606+_select_:[Event]+&source=Sample.materialSampleID,Event.decimalLongitude

I know this was working at some point but i just tried it by drawing a narrow box around hawaii and extending to the west just off Japan.  It returns records extending across the globe.   See:

![image](https://user-images.githubusercontent.com/1154501/69353957-38dc0f00-0c34-11ea-9011-3367c21e1588.png)

 so it appears the latitude functions work but the longitude query is returning everything.  RJ, can you translate the above query into corresponding psql and test there? Perhaps the nested OR function is getting mangled?

**Comment by ewingrj** [comment]
fixed in 508ec2d76b4e14699893417281ff284f4550a613
