### ISSUE TITLE
PlateViewer broken

### ISSUE THREAD

**Issue by jdeck88** [biocodellc/geome-ui#393]
Report from user:
_I am working on entering plate maps for the BOEM project in GEOME.  There seems to be an issue with material sample IDs not showing up when I enter them.  I double checked and know that the metadata is all in GEOME.  Another intern is having the same problem.  Would you be able to help me out with this please?_

i did a bit of testing on this and can't get the plate viewer to work at all.
Try creating a team project under biocode, add a couple of samples with tissue data filled out.
does not recognize materialSamples...

**Comment by ewingrj** [comment]
fixed in f3e4a53982328aa14eff639db436f6ec476d6fe1
