### ISSUE TITLE
Default select join team workspace for about page link

### ISSUE THREAD

**Issue by albarqmaria** [biocodellc/geome-ui#394]
On about page, we have two 'Create a Project' links. 
The first says : 'create a project wthin an existing team'
the second one says 'create a project not part of a team' 
When user clicks the first link, we should have 'Join team workspace' set to true on initialization of project creation wizard.

**Comment by jdeck88** [comment]
This seems like a sensible feature...

**Comment by albarqmaria** [comment]
merged with PR #448
