### ISSUE TITLE
Change styling on navigation tabs to show user what view they're on

### ISSUE THREAD

**Issue by albarqmaria** [biocodellc/geome-ui#398]
When user clicks on any of the workbench navigation tabs, there's no styling difference between the current view and all the others. 
![Screen Shot 2019-09-09 at 7 26 11 AM](https://user-images.githubusercontent.com/35155534/64539334-2c057b80-d2d3-11e9-9a77-66e29659c205.png)

I'd like to give whichever views nav bar is selected a lighter shade of grey to indicate that its selected. 
![Screen Shot 2019-09-09 at 7 26 22 AM](https://user-images.githubusercontent.com/35155534/64539350-30ca2f80-d2d3-11e9-9263-e812a2018ad2.png)

**Comment by albarqmaria** [comment]
Just checking- is this something that is really needed or wanted? Look at it now it doesn't seem super important - lmk

**Comment by jdeck88** [comment]
no, will close it...
