### ISSUE TITLE
show map of collecting event location on event page

### ISSUE THREAD

**Issue by jdeck88** [biocodellc/geome-ui#399]
Current Event page looks like:
![image](https://user-images.githubusercontent.com/1154501/64708985-576e9e80-d46a-11e9-9a14-2157130443d3.png)
But we would like to add leaflet map like:
![image](https://user-images.githubusercontent.com/1154501/64709176-acaab000-d46a-11e9-9b41-29d50166f9b0.png)

**Comment by jdeck88** [comment]
Maria, confer w/ RJ about best way to add mapping functionality (leaflet) to angular framework.  This *should* be a very straightforward thing to add....

**Comment by albarqmaria** [comment]
So This looks just fine for events that do not have photos associated with the event, like so: 
![eventmap](https://user-images.githubusercontent.com/35155534/79961833-eecfb180-848f-11ea-988e-3771c50760b6.png)

But for events that do have photos:
![Screen Shot 2020-04-22 at 11 56 05 AM](https://user-images.githubusercontent.com/35155534/79962061-4241ff80-8490-11ea-8ac5-68307846e644.png)


I could leave this as is, or Option 2: 

![Screen Shot 2020-04-22 at 11 45 23 AM](https://user-images.githubusercontent.com/35155534/79962115-5685fc80-8490-11ea-9da7-7fe53936f47f.png)


Or Option 3: 
![Screen Shot 2020-04-22 at 12 08 15 PM](https://user-images.githubusercontent.com/35155534/79963387-ff812700-8491-11ea-8d1f-efc55c6da3b3.png)
![Screen Shot 2020-04-22 at 12 08 22 PM](https://user-images.githubusercontent.com/35155534/79963412-07d96200-8492-11ea-9071-851b526471fb.png)



Let me know what you think

**Comment by jdeck88** [comment]
i would go for option #2

**Comment by albarqmaria** [comment]
fixed in PR #453
