### ISSUE TITLE
BioSamples link on FASTQ metadata page brings us to wrong SRA location

### ISSUE THREAD

**Issue by jdeck88** [biocodellc/geome-ui#400]
Consider the following FASTQ metadata page:
![image](https://user-images.githubusercontent.com/1154501/64710511-f09eb480-d46c-11e9-9f97-2b3cb2ddcb6e.png)

Clicking on the "BioSamples Link" , brings us to a page of samples belonging to a project... This is not what we expect:
https://www.ncbi.nlm.nih.gov/biosample?LinkName=bioproject_biosample_all&from_uid=496400
Which is a list of all biosamples for a particular project, but not really this particular bioSample.  

We should actually be pointing to the particular bioSample, found at this URL:

https://www.ncbi.nlm.nih.gov/biosample/SAMN10240472

The suffix of the above URL is actually the text belonging to "bioSampleAccession" so it should be easy to construct a proper "BioSamples Link"

**Comment by albarqmaria** [comment]
fixed in PR #419
