### ISSUE TITLE
boolean query fail

### ISSUE THREAD

**Issue by jdeck88** [biocodellc/geome-ui#403]
E.g. under sample, query traditionalKnowledgeNotice it does not offer true/false as you would expect.. it just shows "Choose Value"

![image](https://user-images.githubusercontent.com/1154501/65467429-3583fd00-de16-11e9-80ee-1d2f6993e05a.png)

**Comment by mariadeck** [comment]
Was this on develop or production?

**Comment by mariadeck** [comment]
Also, certain lists (whose column names were not exact matches with their associated list names) currently do not get returned correctly on develop. 
I submitted a PR on August 9th that fixes that issue.

**Comment by ewingrj** [comment]
should be fixed in 8a9b561
