### ISSUE TITLE
dashboard sorting

### ISSUE THREAD

**Issue by jdeck88** [biocodellc/geome-ui#406]
The only thing to add here before release, if it is not too hard is a sorting feature where you can sort by name of project, number of records, hasSRA, hasPhotos.  date of LastUpdate would be useful too to sort on as well (but would require another column).

**Comment by jdeck88** [comment]
Two more dashboard sorting ideas: 
1) for public projects only, sort by latest activity first.  This will emphasize the most relevant projects of interest.

**Comment by albarqmaria** [comment]
fixed in PR #468

**Comment by albarqmaria** [comment]
Do you want to default sort by latest activity?

**Comment by jdeck88** [comment]
Yes, lets just do default sort by latest activity
