### ISSUE TITLE
template validation rule listing

### ISSUE THREAD

**Issue by jdeck88** [biocodellc/geome-ui#418]
The validation rules for materialSampleID have alot of repeated (confusing) elements:

Validation Rules

Type: RequiredValue
Level: ERROR
Type: ValidForURI
Level: ERROR
Type: UniqueValue
Level: ERROR
Type: RequiredValue
Level: ERROR

we need to break out what entity the type refers to.

**Comment by albarqmaria** [comment]
fixed in PR #465
