### ISSUE TITLE
Team Metadata and Landing Page

### ISSUE THREAD

**Issue by jdeck88** [biocodellc/geome-ui#423]
We need to implement a landing page and better metadata/information pertaining to teams.   This issue has two parts: 1) create metadata for teams, and 2) add a team landing page on the interface. The first part of this issue is more closely related to the geome-db repository but will track development here, on the geome-ui repo.  

Metadata elements for Teams
* logo
* description (already present)
* team contact
* team contact email
* website
* documentation URI
* open to collaborate label checkbox : insert stock text and the name of the team in a variable.  provide checkbox so it shows up or not for all projects under team
* preferred citation
* DOI to a publication
* Data DOI
* checkbox of "Open to Collaboration" -- when checked, show this TK label on TEAM page as well as all Project Pages.  

All of these fields should be accessible in the project master configuration -> settings area.

**Comment by jdeck88** [comment]
Duplicate of #408

**Comment by jdeck88** [comment]
Duplicate of #408

**Comment by jdeck88** [comment]
A good start on this issue will be to create a mockup/wireframe of what we want it to look like....

**Comment by jdeck88** [comment]
Here is a mockup diagram of what the page should look like (well, sort of):
[mockup.pdf](https://github.com/biocodellc/geome-ui/files/4246759/mockup.pdf)

**Comment by mariadeck** [comment]
Team Overview Page Mockup Idea 1: 
![Screen Shot 2020-02-26 at 9 54 54 PM](https://user-images.githubusercontent.com/35155534/75377600-3815e180-58e3-11ea-9cb9-b02486947a9f.png)

**Comment by mariadeck** [comment]
Team Overview Page Mockup Idea 2: 
[teamoverviewpagemockup2.pdf](https://github.com/biocodellc/geome-ui/files/4257757/teamoverviewpagemockup2.pdf)

**Comment by mariadeck** [comment]
Team Overview Page Mockup Idea 2:
![Screen Shot 2020-02-26 at 10 33 58 PM](https://user-images.githubusercontent.com/35155534/75380429-179c5600-58e8-11ea-8ff0-ac0452c08208.png)

**Comment by jdeck88** [comment]
Mockup #1 looks better IMO.... however, my only concern is if all teams do not adopt the open to collaborate label then the 3rd box would be completely empty.  So, Mockup #2 maybe is a bit more content-proof... able to adapt to various sized descriptions and metadata fields and TK labelling.... so, given that lets go with Mockup #2

**Comment by mariadeck** [comment]
Ok, I made some tweaks to mockup #2 so that the list of projects have their own ui-view (the box can scroll independently), like the workbench landing page does. Here is mockup 3
![Team Overview Mockup 3](https://user-images.githubusercontent.com/35155534/75409005-7e416400-5928-11ea-9741-a41b548cd6da.png)

**Comment by jdeck88** [comment]
looking good!

**Comment by mariadeck** [comment]
List all Teams View Mockup 1:

![team-dashboard](https://user-images.githubusercontent.com/35155534/75604120-92cb5b00-5ae6-11ea-9534-6aeac3223195.jpg)

**Comment by jdeck88** [comment]
on the "list all teams view Mockup 1", Here are the attributes to show:
 * date of last activity
 * # events
 * # samples
 * # photos
 * # of projects
 * # members

**Comment by mariadeck** [comment]
wouldn't you like the "open to collaborate" attribute on the "list all teams view"?

**Comment by mariadeck** [comment]
Teams List View Mockup 2: 
![teams-list-mockup-2](https://user-images.githubusercontent.com/35155534/75745363-28096200-5d28-11ea-8dcb-185cb6ad93d9.jpg)

**Comment by mariadeck** [comment]
- num of samples
- modules (with bootstrap flags:
tissues module 
fasta
fastq
photos 
diagnostics)
-num of projects
-num of members

**Comment by mariadeck** [comment]
Here's the Teams List Mockup #3 Based on what we talked about:

![Teams List Mockup 3 ](https://user-images.githubusercontent.com/35155534/75843383-12f20900-5de4-11ea-91f6-c1fd4d74b7b5.jpg)

**Comment by albarqmaria** [comment]
Addressed in PR #435
