### ISSUE TITLE
Migrate mapbox usage to new api

### ISSUE THREAD

**Issue by ewingrj** [biocodellc/geome-ui#433]
I got an email saying the api we're using is deprecated and will be killed on 6/1.

It should be fairly easy to migrate. The only place I saw mapbox usage was in `src/app/components/map/map.js`

Looks like we need to follow [this guide](https://docs.mapbox.com/help/troubleshooting/migrate-legacy-static-tiles-api/?mkt_tok=eyJpIjoiWWprell6RTJNR1pqWldRNSIsInQiOiJzcCtNUG5GXC9TRGtXK0RBT1wvNzVRM0VMOWVhXC9OaXMwMkd3d1Fuc2JFXC9YQk43WVhaNDNBTU1FbEtSVHNwRzlqbU9EU3ZDaitwUDRmUlU4c01KQXhnY2h4ZmlTa1FRQ1JtREE2TnNLVXJ0Y0NMTTdOanUycHZvY2FcLzFyVWFCNnFBIn0%3D)

**Comment by albarqmaria** [comment]
fixed with PR #437
