### ISSUE TITLE
Template definitions in mobile styling

### ISSUE THREAD

**Issue by jdeck88** [biocodellc/geome-ui#434]
template definitions on a mobile device need fixing... when clicking on the "DEF" tag, bring up the template definition so it is the only thing on the screen.  Leave AS IS for desktop....

**Comment by albarqmaria** [comment]
I see, like a dialog box, that you need to close before viewing other content?

**Comment by jdeck88** [comment]
yeah, probably...

**Comment by albarqmaria** [comment]
fixed in PR #438
