### ISSUE TITLE
Team-Based Query Interface 

### ISSUE THREAD

**Issue by jdeck88** [biocodellc/geome-ui#439]
I want to enable a query interface specifically for team-based queries.     The way i envision this working is you call the query interface with "team" as a URL parameter.   E.g. ```https://www.geome-db.org/query/?team={TEAM_ID}```
The angular code then fetches the projects that belong to the team, for an example see the "teamToggle function in ```views/query/form/query-form.component.js```

which then calls the api with for example...
```
https://api.geome-db.org/records/Sample/json?limit=10000&page=0&access_token=[ACCESS_TOKEN]&networkId=1&q=_projects_:114,125,61,67,83,75,12,68,69,70,71,76,77,78,72,74,81,79,80,73,82+_select_:%5BEvent%5D+&source=Event.eventID,...
```

The quick way is to write special-purpose angular classes which are loaded for the query interface based on a particular team.    Once the class is called, We would need to fetch a list of projects that belong to a team (similar to how the current query interface works when selecting a team).  Then, On the query interface itself there will be options unique to that team.   

For example:

**Biocode Team Query Page**
Country
Phylum
Genus
Species
MaterialSampleID
Plate Name

**Amphibian Disease Portal Team**
Disease Tested
Country
Year [from] [to]

etc...

we would still leave the existing query page, i think.  If a user selects a Team from the existing query page, we could redirect them to that team's query page....

**Comment by albarqmaria** [comment]
OK, here's mockup 1 on the Amphibian Disease Portal Team's query interface. 
Let me know what changes you want... 

![Screen Shot 2020-03-30 at 12 30 24 PM](https://user-images.githubusercontent.com/35155534/77897374-40ff2780-7282-11ea-88db-3004626eb1c9.png)

With Disease Tested Dropdown Open: 
![Screen Shot 2020-03-30 at 12 28 14 PM](https://user-images.githubusercontent.com/35155534/77897194-04333080-7282-11ea-8a06-a60c63357a29.png)

**Comment by jdeck88** [comment]
The fields we want are:
Disease Tested (dropdown with Bd, Bsal, Other)
Genus (text box)
specific Epithet (text box)
fatal (need to call morbidity on interface) (True/False/Any)
diseaseDetected (need to call it disease Status) (True/False/Any)
Bounding Box search (e.g. see advanced search page)

**Comment by albarqmaria** [comment]
![amphdiseasefinal](https://user-images.githubusercontent.com/35155534/78469074-2fa49800-7726-11ea-9fc6-3a9b6d78cb05.png)
![77897194-04333080-7282-11ea-8a06-a60c63357a29](https://user-images.githubusercontent.com/35155534/78469241-fff68f80-7727-11ea-89d5-f0e97c323d3d.png)

![morbidityOPen](https://user-images.githubusercontent.com/35155534/78469198-a0987f80-7727-11ea-9be8-7e2c72a1b5c0.png)
![diseasestatusOPen](https://user-images.githubusercontent.com/35155534/78469218-e5241b00-7727-11ea-89ad-62a4d42cc543.png)

**Comment by jdeck88** [comment]
This looks good! 
Remember to make it easy to add a customized interface for any team... i think this is a feature all of the teams want.

**Comment by jdeck88** [comment]
can you provide an example for testing this?

**Comment by jdeck88** [comment]
all good.
