### ISSUE TITLE
Customized table results by project

### ISSUE THREAD

**Issue by jdeck88** [biocodellc/geome-ui#469]
The table results for samples, events, and tissues from the query should be customizable by project using the same idea we implemented for the query page.  For example, the amphibian disease portal  opened this issue:

https://github.com/BNHM/AmphibiaWebDiseasePortal/issues/49

In the above issue, there is a request for scientific name, which is really genus+species.  The fix here for all scientificName data displayed in tables should be the same as we implemented in https://github.com/biocodellc/geome-ui/issues/444

**Comment by albarqmaria** [comment]
fixed in PR #480
