### ISSUE TITLE
On select project/ login option

### ISSUE THREAD

**Issue by jdeck88** [biocodellc/geome-ui#47]
if user is not logged in, on select project, ask them if they want to log in and provide a link.

This is so, from splash page navigation the user has the option to see their project.

![image](https://user-images.githubusercontent.com/1154501/41423269-c18c21fa-6faf-11e8-9094-de7447b77bae.png)

**Comment by mariadeck** [comment]
This is now working in my fork, along with your suggestion to re-open the dialog after log-in to take the user where the originally wanted to go: https://github.com/mariadeck/geome-ui/issues/2

However, this is appearing in the console: 
![screen shot 2018-07-30 at 11 36 24 am](https://user-images.githubusercontent.com/35155534/43389832-fa235d2e-93ec-11e8-9d26-52be66f4e837.png)


I will go ahead and submit the PR, let me know if this error needs to be fixed before merging.

**Comment by mariadeck** [comment]
This is fixed in merge #73
