### ISSUE TITLE
Create project with discoverable set to true

### ISSUE THREAD

**Issue by albarqmaria** [biocodellc/geome-ui#472]
On project creation, when user checks the "discoverable" check box and then creates a project, the data thats returned from the newly created project does not reflect the users selection. 

I'm not sure if it's a backend issue or not. The only http service that is doing this is the http "POST"/projects. 
http "PUT"/projects//{projectId} is working correctly.

**Comment by jdeck88** [comment]
For now, i think we should remove the "discoverable" setting from project creation and just enable it in "project settings" which it is already there.

**Comment by jdeck88** [comment]
done..
