### ISSUE TITLE
redirect file through secure connection

### ISSUE THREAD

**Issue by albarqmaria** [biocodellc/geome-ui#486]
When downloading excel workbook from query page on Chrome, gives this message: 

Mixed Content: The site at 'https://geome-db.org/' was loaded over a secure connection, but the file at 'https://api.geome-db.org/files/TaqawBtMbTZtgRZQ2MWx' was redirected through an insecure connection. This file should be served over HTTPS. This download will be blocked in future versions of Chrome. See https://blog.chromium.org/2020/02/protecting-users-from-insecure.html for more details.

**Comment by jdeck88** [comment]
This is covered here https://github.com/biocodellc/geome-db/issues/32
