### ISSUE TITLE
subscribed user not verified properly in UI

### ISSUE THREAD

**Issue by jdeck88** [biocodellc/geome-ui#496]
In the create project view, the ability to add the photos module is retained for "subscribed users" only.  
However, currently, even if a user is subscribed these users still cannot use the photos module.

"subscribed" is set in the database using the subscription_expiration_date field and the JSON response
from the API comes from the following endpoint:

```
http://geome/geome-db/users/{username}?access_token={access_code}
```

and should return something like:
```
{"userId":21,
"username":"jdeck",
"email":"jdeck@berkeley.edu",
"institution":"UCB",
"firstName":"John",
"lastName":"Deck",
"sraUsername":"jdeck",
"sraEmail":"jdeck@berkeley.edu","
sraFirstName":"John",
"sraLastName":"Deck",
"subscribed":true
}
```

Now, in create-project/create-project.html  (see ,for example, line 349) there is a check for subscribed users:
```
 <p ng-show="!$ctrl.isNetworkAdmin && !$ctrl.currentUser.subscribed">
              Note: Only subscribed users can use the photos module. See
              <a ui-sref="about({'#':'subscriptions'})">our about page</a> for more information
            </p>
```
However, when we have a subscribed user logged in this code is still called... (it should not).

I've created mariaa as a subscribed account on develop (verify this using the API call above).

Task is to figure out why subscribed users still are not allowed to add the photos module under
create project.  My guess is that this has something to do with angular internals....

**Comment by albarqmaria** [comment]
fixed in PR #497
