### ISSUE TITLE
Browsing private/discoverable project fails when click on project in TEAM

### ISSUE THREAD

**Issue by jdeck88** [biocodellc/geome-ui#499]
While not logged in...
Goto Team view for futres
Click on one of the projects (e.g. 'FuTRES_Spermophilus.beecheyi_Blois_NorthAmerica_Modern')
it doesn't let you view the project metadata.... i think we need to adjust a setting to allow project metadata to be discoverable.
This will be true for expeditionMetadata and Entity metadata also.

**Comment by jdeck88** [comment]
This came up again... i think it was fixed previously but now not fixed. Re-opening issue.
In DEVELOP version, i created a project under the FuTres team called "Test private but discoverable..."... 
Goto: Team
Click on project "Test private but discoverable..."
it just hangs.

**Comment by albarqmaria** [comment]
fixed, (correctly this time) in PR #542
