### ISSUE TITLE
Project configuration; adding attributes

### ISSUE THREAD

**Issue by jdeck88** [biocodellc/geome-ui#50]
When adding attributes, we need a header that tells us what entity we're adding an attribute for.
This would go just below "Attributes and Rules" tabs and would say something like:
Adding Attributes for Entity = "events"

**Comment by mariadeck** [comment]
This is fixed. Please close issue.

**Comment by rodney757** [comment]
maria, can you add some padding or margin to this? It looks pretty squished

**Comment by mariadeck** [comment]
Ok, I changed it, let me know if that looks better
