### ISSUE TITLE
Hanging team page on certain condition

### ISSUE THREAD

**Issue by jdeck88** [biocodellc/geome-ui#514]
When clicking on discoverable projects and then navigating back to TEAM page things hang.

To reproduce, goto FuTRES Team and click on a private/discoverable project, e.g.:
"FuTRES_Aepyceros_Villaseñor_Africa_Modern Overview"
Then click on the little blue button to go back to the FuTRES Team. Things hang.
Need to hard reload page to get back to business. 

This only happens with private/discoverable=true projects.  The javascript error i see is:
```
angular.js:15570 TypeError: Cannot read property 'entities' of undefined
    at e.value (team-overview.component.js:23)
    at angular.js:10546
    at $ (angular.js:395)
    at ae (angular.js:10535)
    at angular.js:9835
    at angular.js:9700
    at Object.<anonymous> (viewDirective.js:349)
    at angular.js:1390
    at Ne (angular.js:11269)
    at ae (angular.js:10588)
``` 
and also see following screenshot:
![image](https://user-images.githubusercontent.com/1154501/93152363-6efee980-f6b3-11ea-9751-3b1dde4d1235.png)

A little blue twirly icon comes up and never shows us the Team page again (until we hard reload).
Looks like purely an angular issue.

**Comment by albarqmaria** [comment]
Was this fixed by the recently merged PR?

**Comment by jdeck88** [comment]
yes, fixed by recent pr, closing..
