### ISSUE TITLE
share all saved templates amongst all projects in a Team

### ISSUE THREAD

**Issue by mkoo** [biocodellc/geome-ui#529]
I've created data template configurations for different scenarios of users: one for field specimens, one for museum specimens. I would like each Team project to have these available in their own Template Generator page. That is not available currently. The public project I have to generate templates: https://geome-db.org/workbench/template?projectId=291 is also limited-- only logged in users can download these saved configurations. (For now I may download these preconfigured saved templates as XLS and host on the portal separately as a workaround.)

This was copied over from the AmphibianDisease issue list ([Geome request](https://github.com/BNHM/AmphibiaWebDiseasePortal/issues/102))

**Comment by jdeck88** [comment]
i've consolidated  #502 and #503 into  #529.  i don't think a team template will look any different than a project template. Here is how we want things to appear:

 1. show all templates for all projects under a particular team (currently only shows project templates)
 2. If the user is not logged in they can still see all the templates that are created for all teams (currently this is not available for guests)
 3. If a user is logged in they can edit their own templates (this is current functionality)

**Comment by albarqmaria** [comment]
fixed with PR #551
