### ISSUE TITLE
Improper Grammar!

### ISSUE THREAD

**Issue by jdeck88** [biocodellc/geome-ui#535]
Looks like an "s" is added to entities in the record view. For example,  Event becomes Events and Sample becomes Samples.  Works fine except for Diagnostics becomes Diagnosticss

![image](https://user-images.githubusercontent.com/1154501/96334667-502fa200-1027-11eb-8ea6-d37ef0c93076.png)

**Comment by albarqmaria** [comment]
fixed in PR #539
