### ISSUE TITLE
Record landing page expedition link should goto expedition landing page

### ISSUE THREAD

**Issue by jdeck88** [biocodellc/geome-ui#538]
Follow this URL:
https://geome-db.org/record/ark:/21547/DUx2161
The Expedition Code link brings you to a query page to query the records for this expedition.  
e.g. https://geome-db.org/query?q=_projects_:282%20and%20_expeditions_:EFMD

However, i think we want to instead goto the expedition landing page:
e.g. that accessible at: https://n2t.net/ark:/21547/DUu2
--

**Comment by albarqmaria** [comment]
The API call made from Record View to:
https://api.geome-db.org/records/ark:/21547/DUx2161?includeParent&includeChildren
Needs to include expeditionIdentifier or BCID, currently expeditionCode is the only expedition data returned from the API

**Comment by albarqmaria** [comment]
Was able to add a UI workaround by making an addition API call to expedition.service for the identifier. See PR #544
