### ISSUE TITLE
splash page "about" navigation

### ISSUE THREAD

**Issue by jdeck88** [biocodellc/geome-ui#54]
When clicking the "about" graphic on the splash page, we are nicely directed to the information at the bottom of the page.  However, in my first navigation of this i intuitively pressed the back button on the browser and did not go back to geome home.  
Can we make the "about" click an HREF target so that when it is clicked the back button works to get us back to Geome home itself.

**Comment by rodney757** [comment]
The problem with an href is when you click about, then scroll up and click about again it doesn't work

looks like we may need to use the history api & modify the state when the "about" button is clicked. https://docs.angularjs.org/api/ng/service/$location#state
