### ISSUE TITLE
Validation WARNING & ERRORs

### ISSUE THREAD

**Issue by jdeck88** [biocodellc/geome-ui#56]
i have noticed that in cases where a WARNING is thrown for one rule on  worksheet along with an ERROR on the same worksheet, that both WARNING and ERROR get lumped as ERROR.  Is there a test for a validation run with a WARNING and ERROR together .

See following set of files to replicate issue.
[TIMOR_Tissues.txt](https://github.com/biocodellc/geome-ui/files/2177423/TIMOR_Tissues.txt)
[TIMOR_Specimens.txt](https://github.com/biocodellc/geome-ui/files/2177424/TIMOR_Specimens.txt)
[TIMOR_Collecting_Events.txt](https://github.com/biocodellc/geome-ui/files/2177425/TIMOR_Collecting_Events.txt)

**Comment by rodney757** [comment]
> Is there a test for a validation run with a WARNING and ERROR together
what do you mean here?

is this in the ui? or via the uploader script?

This is just how we display it in the ui. The server response separates them out.

**Comment by rodney757** [comment]
fixed
