### ISSUE TITLE
Useful info for downloadable XLSX template - Instructions tab

### ISSUE THREAD

**Issue by mkoo** [biocodellc/geome-ui#574]
On the first tab of the XLSX, I suggest adding two extra rows to the Instruction tab with this text:
```
**Additional Fields**
If additional fields are needed to capture all data collected for a project, refer to the Geome Workbench Template Generator
 (https://geome-db.org/workbench/template) for your project or team. Any of those fields may be added to Samples 
 as long as the data conform to the listed definition and data type.
```
So it would look like this:
![Screen Shot 2022-01-22 at 12 43 02 PM](https://user-images.githubusercontent.com/2523089/150850119-6379a76e-e1c0-4438-b980-21c4b4d1ff87.png)

Thanks!

**Comment by jdeck88** [comment]
done
