### ISSUE TITLE
PlateMatcher

### ISSUE THREAD

**Issue by jdeck88** [biocodellc/geome-ui#59]
Need to create a plate-matcher similiar to what is found at:
http://biocode.berkeley.edu/query_platematcher.html

Create an angular view for the plate and use the existing query service to fetch children of a given sample to mock-up calls.  Do this in a new branch.

**Comment by rodney757** [comment]
this is implemented. [this issue](https://github.com/biocodellc/geome-db/issues/23) contains some improvements that should be made for plates & data integrity, but the ui is done & I think has feature parity w/ the old biocode
