### ISSUE TITLE
Standardize and Fix Download Functionality in several spots

### ISSUE THREAD

**Issue by jdeck88** [biocodellc/geome-ui#62]
Need to be able to download events/samples/tissues as worksheets on a single XLSX workbook In the Project Overview page.   There are a few implementations of downloading data and we should standardize them.  Following is what we want:

**Project Overview Page:**
1.   Individual Expeditions: "CSV Archive" , "Excel Workbook", "FASTA", "FASTQ-SRA metadata"

2. Entire project: "CSV Archive"

**My Expeditions Page**

1. link on right: "CSV Archive" , "Excel Workbook", "FASTA", "FASTQ-SRA metadata"

**Query Page**
1. Download: "CSV Archive", "FASTA"

All of this should be trivial to add, backend supports this, just need to generate the appropriate query and call queryExcel in the api

**Comment by rodney757** [comment]
I assume this is on the "Project Overview" page?

Should be trivial to add, backend supports this, just need to generate the appropriate query and call `queryExcel` in the api

**Comment by rodney757** [comment]
this is done, only difference is that I remove the Fasta option from dashboad & expedition views and include the files in the CSV Archive.

Another change is all query downloads are zipped now
