### ISSUE TITLE
Add field "Description" to expeditions within a project

### ISSUE THREAD

**Issue by tweedts** [biocodellc/geome-ui#627]
My colleagues have requested that I designate expeditions in GEOME that have passed some final data review process. _Projects_ have a fillable description field text box that can include funding acknowledgement language, etc, but I will also need descriptions that are unique to individual _expeditions_ within a project. E.g. "This expedition data has undergone final QAQC review by NOAA and NMNH data managers, year-month-day."

Could we add a 'description' text field for individual expeditions within a project so that I can add key funding language and data review status language for each individual expedition?

**Comment by jdeck88** [comment]
This has expedition field has been added to the Biocode Team
