### ISSUE TITLE
Expired/invalid reset token after requesting password reset

### ISSUE THREAD

**Issue by jdeck88** [biocodellc/geome-ui#63]
To reproduce, click on forgot password button on login screen.  
Get email and click link.
Type in a new password and the following comes up:
![image](https://user-images.githubusercontent.com/1154501/42788462-7c4de2e4-8914-11e8-8e19-12f41e030e0d.png)

**Comment by rodney757** [comment]
typo in props file which made the link go to biscicol.org. 

change the to `develop.geome-db.org` and it should work.

**Comment by rodney757** [comment]
it works
