### ISSUE TITLE
Update project admin UI to only allow modifications allowed by the NetworkConfig

### ISSUE THREAD

**Issue by jdeck88** [biocodellc/geome-ui#65]
Still allow user to view these but for now we want to disable the editing capability from the UI interface

**Comment by rodney757** [comment]
This is no longer necessary now that we have networks implemented. Now we need to update the ui to take into account the network config when updating a project config

**Comment by rodney757** [comment]
fixed in 8a7b1839545103f0d18dc302d8b47be35de6a3dd & other recent commits
