### ISSUE TITLE
Erratic behavior when loading....

### ISSUE THREAD

**Issue by jdeck88** [biocodellc/geome-ui#72]
Using the attached (ACEH_Specimens.txt) file, i see different things happening each time i try and validate.    Logged in as biocode user and select "samples worksheet", choose expedition ACEH, and validate only.  The following behaviours were observed:
  * Sometimes i get an empty dialog box with a spinner, no text and then it brings me to the "Results" tab with no content.  
  * Sometimes i get a message in the dialog box, with the dialog box appearing for several seconds and the dialog disappears on its own and no content in the Results window.  
  * Sometimes i get a message in the dialog box and it waits for me to press OK and then i get a message in the Results window (desired behaviour). 

[ACEH_Specimens.txt](https://github.com/biocodellc/geome-ui/files/2227849/ACEH_Specimens.txt)

**Comment by rodney757** [comment]
okay, this is fixed. When the validation was successful, it wasn't informing the user.

The dialog will auto-close when you are validating. There is no need to push "ok" if we aren't uploading.

The spinner appears while we don't have any status. To display. We do a minimal amount of work on the server to setup async validation, and then return an id that can be used to fetch the status of that validation. However if validation completes quickly (which happens w/ csv/tsv files), the validation is completed before we can fetch the first status update. I've added an "Uploading..." message to the status in the ui so it at least shows something now.

If you are uploading, and an error occurs, that is when the "OK" button appears.
