### ISSUE TITLE
state change when logging out from query page 

### ISSUE THREAD

**Issue by mariadeck** [biocodellc/geome-ui#74]
When the active state is 'query' and the user logs out of their account, the state changes to 'home'. this appears in the console 
![screen shot 2018-08-02 at 9 08 14 pm](https://user-images.githubusercontent.com/35155534/43605474-aef771a6-9698-11e8-934a-272e40c39565.png)

**Comment by mariadeck** [comment]
I'm realizing that you probably just meant for it to do that... but if you'd like to change the functionality, I can change 'ui-sref="home"' on line 41 of src/app/components/header/header.html to 'ui-sref-opts="{reload: true}"' 
which will reload workbench and query states when a user logs out rather than routing them to home view

**Comment by rodney757** [comment]
the change sounds good

**Comment by mariadeck** [comment]
This has already been fixed in one of your latest changes
