### ISSUE TITLE
my expeditions and project overview

### ISSUE THREAD

**Issue by jdeck88** [biocodellc/geome-ui#76]
these two sections appear to display the same information. 

recommend removing "my expeditions" since it displays just part of the information that project overview does.  

Check with RJ first to see if there is a reason for "my expeditions"  under the Admin section.

**Comment by rodney757** [comment]
we should leave my expeditions. That shows only your expeditions instead of all the projects expeditions and is how you administer the expedition (click on one).

Change the title, make public/private. Eventually add members to collaborate on the expedition.

**Comment by jdeck88** [comment]
OK, then lets add explanatory text to the top of my expeditions.  This should read:

Expeditions belong to {logged in username}
The following expeditions belong to {logged in username} and may not represent a comprehensive list of expeditions for this project, which can be found on the <a href=''>project overview</a> link.  Select each of your expeditions below to change title, permissions and collaborators.

**Comment by jdeck88** [comment]
(Maria, you can go ahead and work on this change)
