### ISSUE TITLE
Method for naming expeditions in new system

### ISSUE THREAD

**Issue by jdeck88** [biocodellc/geome-ui#81]
In the old system, if i created an expedition called "Test" it was called "Test spreadsheet" in online docs.
In the new system, if i create an expedition called "Test" it is named simply "Test".

I think we should drop the " spreadsheet" off of the expedition names on importing expeditions into new system

John

**Comment by rodney757** [comment]
the old system only collected the expedition_code and auto generated the title

**Comment by rodney757** [comment]
done for current expeditions, and the migration script should do this as well
