### ISSUE TITLE
Fix pagination in Project Overview view

### ISSUE THREAD

**Issue by jdeck88** [biocodellc/geome-ui#83]
Successfully validated and loaded a "test" expedition into develop version of UI.
it shows up under "my expeditions", has visibility public but doesn't appear under "Project Overview"

Also, logged in as dipnetCurator and "my expeditions" only shows Test, not any of the other expeditions.  Seems like a different user owns the rest of the loaded expeditions?  This is not the case for the production site (where dipnetCurator owns all expeditions).

**Comment by rodney757** [comment]
this is b/c pagination is broken on the project overview view. I thought I made an issue on gh, but it turns out I only made myself a todo.
