### ISSUE TITLE
Default Columns in Configuration for DIPNet

### ISSUE THREAD

**Issue by jdeck88** [biocodellc/geome-ui#93]
Need to change default columns in configuration to match what was in DIPNet previously.
See columns below.
![image](https://user-images.githubusercontent.com/1154501/44300011-bcca7d00-a2b4-11e8-9bfa-addca79b1d5c.png)

**Comment by rodney757** [comment]
we should also add the appropriate groups to the events columns & probably sort the attributes how they were before (I know Michelle spent time doing that)

**Comment by jdeck88** [comment]
This is fixed... not EXACTLY how it was before since it seems we need to maintain the order of the Entities first and then put the required columns at the top of each.  In any case, its much cleaner now.
