### ISSUE TITLE
DIPNet admin issues

### ISSUE THREAD

**Issue by jdeck88** [biocodellc/geome-ui#94]
NOTE: this error exists only in the DEVELOP instance... does not appear on PROD.
If i login as dipnetCurator to the develop site it does not display "project settings".
If i login as biocode to the develop site it displays "project settings" but it does not let me alter the configuration... it tells me i am not an admin.

Seems like there is some confusion here.

**Comment by rodney757** [comment]
this has to do w/ my migration script. It disables some triggers at start, and should re-enable them at end (but sometimes this doesn't happen).

fixed now. dipnetCurator is the admin
